Add corsheaders lib, remove parser_classes from UserList view
Kh-011-WebUIPython/lit pull request #15
Opened 2018-01-20 22:45 UTC by exceedcat

2018-01-21 09:54 UTC, maxkrivich approved these changes

2018-01-21 10:00 UTC, maxkrivich commented
@exceedcat remove from .travis.yml lines 10, 21. 23-24 and commit changes. That should fix the problem with Travis CI.

2018-01-21 10:01 UTC, maxkrivich requested changes
@exceedcat remove from .travis.yml lines 10, 21, 23-24 and commit changes. That should fix the problem with Travis CI.

2018-01-22 16:46 UTC, exceedcat commented
I've added `django-cors-headers` to requirements.

2018-01-23 12:42 UTC, maxkrivich approved these changes

2018-01-23 12:42 UTC, merged